Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "../", "/vagrant_data"

  # Менеджер
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.101"
    # manager.vm.network "forwarded_port", guest: 80, host: 8080
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    manager.vm.provision "shell", path: "C:/Users/yanam/школа 21/Devops/DevOps_7.ID_1219717-1/vagrant/swarm_manager.sh"
  end

  # Воркеры
  ["worker01", "worker02"].each_with_index do |worker_name, index|
    config.vm.define worker_name do |worker|
      worker.vm.hostname = worker_name
      worker.vm.network "private_network", ip: "192.168.56.#{102 + index}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
      worker.vm.provision "shell", path: "C:/Users/yanam/школа 21/Devops/DevOps_7.ID_1219717-1/vagrant/docker-worker.sh"
    end
  end

  config.vm.boot_timeout = 600
end
